### ISSUE TITLE
support classnames/bind

### ISSUE THREAD

**Issue by DragorWW** [avaly/babel-plugin-inline-classnames#2]
What you think about support [classnames/bind](https://github.com/JedWatson/classnames#alternate-bind-version-for-css-modules)?

example code:
```js
import classNames from 'classnames/bind';
import styles from './styles.css';

var cx = classNames.bind(styles);

cx('foo', 'bar');
```
expect:
```js
import styles from './styles.css';

(styles.foo || '') + ' ' + (styles.bar || '');"
```

----
update by [comment](https://github.com/avaly/babel-plugin-inline-classnames/issues/2#issuecomment-345536249)

**Comment by avaly** [comment]
I assume your example code should be something like (according to the package docs):

```js
cx('foo', 'bar');
```

I'll try to get this in the future, but please feel free to submit a PR if you need it faster.

**Comment by DragorWW** [comment]
@avaly I trying make PR, but, my skils in babel api is low.
